function LoadingIndicator({ show = true }: { show?: boolean }) {
    const svgWidth = "w-30";
    const svgHeight = "h-30";

    const svg1 = (
        <svg
            fill="hsl(228, 97%, 42%)"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
            className={`${svgWidth} ${svgHeight}`}
        >
            <rect x="1" y="1" width="7.33" height="7.33">
                <animate
                    id="spinner_oJFS"
                    begin="0;spinner_5T1J.end+0.2s"
                    attributeName="x"
                    dur="0.6s"
                    values="1;4;1"
                />
                <animate
                    begin="0;spinner_5T1J.end+0.2s"
                    attributeName="y"
                    dur="0.6s"
                    values="1;4;1"
                />
                <animate
                    begin="0;spinner_5T1J.end+0.2s"
                    attributeName="width"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
                <animate
                    begin="0;spinner_5T1J.end+0.2s"
                    attributeName="height"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
            </rect>
            <rect x="8.33" y="1" width="7.33" height="7.33">
                <animate
                    begin="spinner_oJFS.begin+0.1s"
                    attributeName="x"
                    dur="0.6s"
                    values="8.33;11.33;8.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.1s"
                    attributeName="y"
                    dur="0.6s"
                    values="1;4;1"
                />
                <animate
                    begin="spinner_oJFS.begin+0.1s"
                    attributeName="width"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.1s"
                    attributeName="height"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
            </rect>
            <rect x="1" y="8.33" width="7.33" height="7.33">
                <animate
                    begin="spinner_oJFS.begin+0.1s"
                    attributeName="x"
                    dur="0.6s"
                    values="1;4;1"
                />
                <animate
                    begin="spinner_oJFS.begin+0.1s"
                    attributeName="y"
                    dur="0.6s"
                    values="8.33;11.33;8.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.1s"
                    attributeName="width"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.1s"
                    attributeName="height"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
            </rect>
            <rect x="15.66" y="1" width="7.33" height="7.33">
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="x"
                    dur="0.6s"
                    values="15.66;18.66;15.66"
                />
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="y"
                    dur="0.6s"
                    values="1;4;1"
                />
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="width"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="height"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
            </rect>
            <rect x="8.33" y="8.33" width="7.33" height="7.33">
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="x"
                    dur="0.6s"
                    values="8.33;11.33;8.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="y"
                    dur="0.6s"
                    values="8.33;11.33;8.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="width"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="height"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
            </rect>
            <rect x="1" y="15.66" width="7.33" height="7.33">
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="x"
                    dur="0.6s"
                    values="1;4;1"
                />
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="y"
                    dur="0.6s"
                    values="15.66;18.66;15.66"
                />
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="width"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.2s"
                    attributeName="height"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
            </rect>
            <rect x="15.66" y="8.33" width="7.33" height="7.33">
                <animate
                    begin="spinner_oJFS.begin+0.3s"
                    attributeName="x"
                    dur="0.6s"
                    values="15.66;18.66;15.66"
                />
                <animate
                    begin="spinner_oJFS.begin+0.3s"
                    attributeName="y"
                    dur="0.6s"
                    values="8.33;11.33;8.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.3s"
                    attributeName="width"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.3s"
                    attributeName="height"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
            </rect>
            <rect x="8.33" y="15.66" width="7.33" height="7.33">
                <animate
                    begin="spinner_oJFS.begin+0.3s"
                    attributeName="x"
                    dur="0.6s"
                    values="8.33;11.33;8.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.3s"
                    attributeName="y"
                    dur="0.6s"
                    values="15.66;18.66;15.66"
                />
                <animate
                    begin="spinner_oJFS.begin+0.3s"
                    attributeName="width"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.3s"
                    attributeName="height"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
            </rect>
            <rect x="15.66" y="15.66" width="7.33" height="7.33">
                <animate
                    id="spinner_5T1J"
                    begin="spinner_oJFS.begin+0.4s"
                    attributeName="x"
                    dur="0.6s"
                    values="15.66;18.66;15.66"
                />
                <animate
                    begin="spinner_oJFS.begin+0.4s"
                    attributeName="y"
                    dur="0.6s"
                    values="15.66;18.66;15.66"
                />
                <animate
                    begin="spinner_oJFS.begin+0.4s"
                    attributeName="width"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
                <animate
                    begin="spinner_oJFS.begin+0.4s"
                    attributeName="height"
                    dur="0.6s"
                    values="7.33;1.33;7.33"
                />
            </rect>
        </svg>
    );
    const svg2 = (
        <svg
            fill="hsl(228, 97%, 42%)"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
            className={`${svgWidth} ${svgHeight}`}
        >
            <circle cx="12" cy="12" r="0">
                <animate
                    id="spinner_0Nme"
                    begin="0;spinner_ITag.begin+0.4s"
                    attributeName="r"
                    calcMode="spline"
                    dur="1.2s"
                    values="0;11"
                    keySplines=".52,.6,.25,.99"
                    fill="freeze"
                />
                <animate
                    begin="0;spinner_ITag.begin+0.4s"
                    attributeName="opacity"
                    calcMode="spline"
                    dur="1.2s"
                    values="1;0"
                    keySplines=".52,.6,.25,.99"
                    fill="freeze"
                />
            </circle>
            <circle cx="12" cy="12" r="0">
                <animate
                    id="spinner_f83A"
                    begin="spinner_0Nme.begin+0.4s"
                    attributeName="r"
                    calcMode="spline"
                    dur="1.2s"
                    values="0;11"
                    keySplines=".52,.6,.25,.99"
                    fill="freeze"
                />
                <animate
                    begin="spinner_0Nme.begin+0.4s"
                    attributeName="opacity"
                    calcMode="spline"
                    dur="1.2s"
                    values="1;0"
                    keySplines=".52,.6,.25,.99"
                    fill="freeze"
                />
            </circle>
            <circle cx="12" cy="12" r="0">
                <animate
                    id="spinner_ITag"
                    begin="spinner_0Nme.begin+0.8s"
                    attributeName="r"
                    calcMode="spline"
                    dur="1.2s"
                    values="0;11"
                    keySplines=".52,.6,.25,.99"
                    fill="freeze"
                />
                <animate
                    begin="spinner_0Nme.begin+0.8s"
                    attributeName="opacity"
                    calcMode="spline"
                    dur="1.2s"
                    values="1;0"
                    keySplines=".52,.6,.25,.99"
                    fill="freeze"
                />
            </circle>
        </svg>
    );
    const svg3 = (
        <svg
            viewBox="0 0 135 140"
            xmlns="http://www.w3.org/2000/svg"
            className="w-16 h-16"
        >
            <rect y="10" width="15" height="120" rx="6" fill="hsl(228, 97%, 42%)">
                <animate
                    attributeName="height"
                    begin="0.5s"
                    dur="1s"
                    values="120;110;100;90;80;70;60;50;40;140;120"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
                <animate
                    attributeName="y"
                    begin="0.5s"
                    dur="1s"
                    values="10;15;20;25;30;35;40;45;50;0;10"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
            </rect>
            <rect x="30" y="10" width="15" height="120" rx="6" fill="hsl(228, 97%, 42%)">
                <animate
                    attributeName="height"
                    begin="0.25s"
                    dur="1s"
                    values="120;110;100;90;80;70;60;50;40;140;120"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
                <animate
                    attributeName="y"
                    begin="0.25s"
                    dur="1s"
                    values="10;15;20;25;30;35;40;45;50;0;10"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
            </rect>
            <rect x="60" width="15" height="140" rx="6" fill="hsl(228, 97%, 42%)">
                <animate
                    attributeName="height"
                    begin="0s"
                    dur="1s"
                    values="120;110;100;90;80;70;60;50;40;140;120"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
                <animate
                    attributeName="y"
                    begin="0s"
                    dur="1s"
                    values="10;15;20;25;30;35;40;45;50;0;10"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
            </rect>
            <rect x="90" y="10" width="15" height="120" rx="6" fill="hsl(228, 97%, 42%)">
                <animate
                    attributeName="height"
                    begin="0.25s"
                    dur="1s"
                    values="120;110;100;90;80;70;60;50;40;140;120"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
                <animate
                    attributeName="y"
                    begin="0.25s"
                    dur="1s"
                    values="10;15;20;25;30;35;40;45;50;0;10"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
            </rect>
            <rect x="120" y="10" width="15" height="120" rx="6" fill="hsl(228, 97%, 42%)">
                <animate
                    attributeName="height"
                    begin="0.5s"
                    dur="1s"
                    values="120;110;100;90;80;70;60;50;40;140;120"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
                <animate
                    attributeName="y"
                    begin="0.5s"
                    dur="1s"
                    values="10;15;20;25;30;35;40;45;50;0;10"
                    calcMode="linear"
                    repeatCount="indefinite"
                />
            </rect>
        </svg>
    );

    const randomSvg = [svg1, svg2, svg3][Math.floor(Math.random() * 3)];
    if (!show) return null;

    return (
        <div className="fixed inset-0 flex justify-center items-center backdrop-blur-sm bg-black/20 z-50">
            {randomSvg}
        </div>
    );
}

export default LoadingIndicator;
